<?php

/**
 * Featured icons shown before search; full set comes from Bootstrap Icons CSS via BootstrapIconRegistry.
 * search_aliases: Persian/English keywords → icon name fragments for picker search.
 */
return [
    'featured' => [
        'bi-wifi', 'bi-snow', 'bi-snow2', 'bi-sun', 'bi-sun-fill', 'bi-moon', 'bi-moon-stars',
        'bi-lightning', 'bi-lightning-charge', 'bi-droplet', 'bi-droplet-fill', 'bi-water',
        'bi-fire', 'bi-thermometer-half', 'bi-wind', 'bi-fan', 'bi-plug', 'bi-plug-fill',
        'bi-house', 'bi-house-door', 'bi-house-heart', 'bi-building', 'bi-buildings', 'bi-houses',
        'bi-door-open', 'bi-door-closed', 'bi-key', 'bi-key-fill', 'bi-lock', 'bi-lock-fill',
        'bi-shield-check', 'bi-shield-lock', 'bi-camera-video', 'bi-camera', 'bi-bed',
        'bi-lamp', 'bi-lamp-fill', 'bi-lightbulb', 'bi-lightbulb-fill', 'bi-cup-hot', 'bi-cup-hot-fill',
        'bi-egg-fried', 'bi-trash', 'bi-recycle', 'bi-badge-wc', 'bi-badge-wc-fill', 'bi-bucket',
        'bi-brush', 'bi-tools', 'bi-wrench', 'bi-tv', 'bi-tv-fill', 'bi-speaker', 'bi-music-note',
        'bi-controller', 'bi-laptop', 'bi-phone', 'bi-car-front', 'bi-car-front-fill',
        'bi-p-circle', 'bi-p-square', 'bi-ev-station', 'bi-ev-front', 'bi-fuel-pump', 'bi-bicycle',
        'bi-geo-alt', 'bi-map', 'bi-pin-map', 'bi-compass', 'bi-tree', 'bi-tree-fill',
        'bi-flower1', 'bi-flower2', 'bi-umbrella', 'bi-umbrella-fill', 'bi-cloud-sun', 'bi-cloud-rain',
        'bi-cloud-lightning', 'bi-rainbow', 'bi-snow3', 'bi-heart', 'bi-star', 'bi-people',
        'bi-person-wheelchair', 'bi-universal-access', 'bi-person-hearts', 'bi-hospital',
        'bi-bell', 'bi-alarm', 'bi-clock', 'bi-calendar-check', 'bi-cash-coin', 'bi-credit-card',
        'bi-wallet2', 'bi-bag', 'bi-cart', 'bi-box', 'bi-telephone', 'bi-chat', 'bi-envelope',
        'bi-window', 'bi-arrows-fullscreen', 'bi-eye', 'bi-shop', 'bi-truck', 'bi-bank',
        'bi-safe', 'bi-piggy-bank', 'bi-battery-charging', 'bi-globe', 'bi-book', 'bi-image',
        'bi-headphones', 'bi-smartwatch', 'bi-tablet', 'bi-display', 'bi-router', 'bi-bluetooth',
        'bi-signal', 'bi-speedometer2', 'bi-list-check', 'bi-stopwatch', 'bi-volume-up', 'bi-mic',
        'bi-webcam', 'bi-keyboard', 'bi-printer', 'bi-flag', 'bi-award', 'bi-trophy', 'bi-gem',
        'bi-patch-check', 'bi-info-circle', 'bi-check-circle', 'bi-gift', 'bi-balloon', 'bi-stars',
        'bi-sunrise', 'bi-sunset', 'bi-tsunami', 'bi-hurricane', 'bi-tornado', 'bi-binoculars',
        'bi-sign-no-parking', 'bi-sign-stop', 'bi-hdd', 'bi-power', 'bi-fingerprint',
        'bi-house-lock', 'bi-house-check', 'bi-egg', 'bi-apple', 'bi-basket', 'bi-basket-fill',
        'bi-cake2', 'bi-cookie', 'bi-droplet-half', 'bi-moisture', 'bi-cloud', 'bi-cloudy',
        'bi-emoji-sunglasses', 'bi-sunglasses', 'bi-backpack', 'bi-tropical-storm',
        'bi-layout-text-window', 'bi-paint-bucket', 'bi-hammer', 'bi-scissors',
    ],

    'search_aliases' => [
        'تاب' => ['umbrella', 'sun', 'sunglasses', 'tree', 'flower', 'balloon', 'wind'],
        'سایبان' => ['umbrella', 'sun', 'shade'],
        'آویز' => ['umbrella', 'tree', 'balloon'],
        'استخر' => ['water', 'droplet', 'tsunami', 'moisture', 'waves', 'cloud-rain', 'tropical'],
        'حمام' => ['droplet', 'water', 'badge-wc', 'bucket', 'moisture'],
        'سرویس' => ['badge-wc', 'droplet', 'water'],
        'توالت' => ['badge-wc'],
        'آشپزخانه' => ['cup-hot', 'egg', 'microwave', 'basket', 'fridge', 'oven', 'cookie', 'cup'],
        'پارکینگ' => ['p-circle', 'p-square', 'car-front', 'sign-no-parking', 'garage', 'ev'],
        'وایفای' => ['wifi'],
        'اینترنت' => ['wifi', 'router', 'signal'],
        'تهویه' => ['fan', 'wind', 'snow', 'thermometer'],
        'کولر' => ['snow', 'fan', 'thermometer-snow'],
        'بخاری' => ['fire', 'thermometer-sun', 'sun'],
        'گرمایش' => ['fire', 'thermometer-sun', 'sun'],
        'سرمایش' => ['snow', 'fan', 'thermometer-snow'],
        'تلویزیون' => ['tv'],
        'صدا' => ['speaker', 'volume', 'music', 'headphones'],
        'موسیقی' => ['music', 'speaker'],
        'باغ' => ['tree', 'flower', 'umbrella'],
        'حیاط' => ['tree', 'flower', 'house', 'umbrella'],
        'باربیکیو' => ['fire', 'cup-hot', 'egg-fried'],
        'کباب' => ['fire', 'cup-hot'],
        'حیوان' => ['paw', 'bug'],
        'حیوان خانگی' => ['heart', 'person-hearts'],
        'کودک' => ['person', 'balloon', 'gift'],
        'نوزاد' => ['balloon', 'heart'],
        'معاف' => ['wheelchair', 'universal-access'],
        'ویلچر' => ['wheelchair', 'universal-access'],
        'آسانسور' => ['arrow-up', 'building', 'ladder'],
        'پله' => ['ladder', 'stairs'],
        'نظافت' => ['brush', 'bucket', 'trash', 'recycle'],
        'لباسشویی' => ['bucket', 'water', 'droplet'],
        'اتو' => ['fire', 'sun'],
        'امنیت' => ['shield', 'lock', 'camera', 'eye', 'fingerprint'],
        'دوربین' => ['camera', 'webcam', 'cctv'],
        'کلید' => ['key'],
        'قفل' => ['lock'],
        'پول' => ['cash', 'coin', 'wallet', 'credit-card', 'bank'],
        'پرداخت' => ['cash', 'credit-card', 'wallet'],
        'رزرو' => ['calendar', 'clock', 'check-circle'],
        'موقعیت' => ['geo', 'map', 'pin-map', 'compass'],
        'مکان' => ['geo', 'map', 'pin'],
        'ساحل' => ['umbrella', 'sun', 'water', 'tsunami', 'sunglasses'],
        'کوه' => ['tree', 'binoculars'],
        'برق' => ['lightning', 'plug', 'power', 'battery'],
        'گاز' => ['fire', 'fuel'],
        'آب' => ['droplet', 'water', 'moisture'],
        'یخچال' => ['snow', 'thermometer-snow'],
        'میز' => ['table'],
        'صندلی' => ['chair'],
        'تخت' => ['house', 'lamp'],
        'اتاق' => ['door', 'house', 'key'],
        'استقبال' => ['bell', 'person', 'door'],
        'پذیرش' => ['bell', 'person'],
        'tab' => ['umbrella', 'sun', 'table', 'layout'],
        'pool' => ['water', 'droplet', 'tsunami', 'moisture'],
        'hammock' => ['umbrella', 'tree', 'balloon'],
        'bbq' => ['fire', 'cup-hot'],
        'garden' => ['tree', 'flower'],
        'parking' => ['p-circle', 'car-front'],
        'wifi' => ['wifi'],
        'ac' => ['snow', 'fan'],
        'tv' => ['tv'],
        'bath' => ['droplet', 'badge-wc', 'water'],
        'kitchen' => ['cup-hot', 'egg', 'basket'],
    ],
];
