<?php

return [
    'order_created_renter' => [
        'pattern_id' => config('sms.patterns.order_created_renter'),
        'title' => 'ثبت درخواست رزرو — مهمان',
        'recipient' => 'مهمان',
        'trigger' => 'ایجاد سفارش (رزرو)',
        'source' => 'OrderObserver::created',
        'category' => 'orders',
        'parameters' => ['HOME_NAME', 'CONSULTANT_NAME', 'CONSULTANT_MOBILE'],
        'description' => 'مشاور شما (#CONSULTANT_NAME#) — برای سوالات بیشتر با مشاور خود تماس بگیرید: #CONSULTANT_MOBILE#',
    ],
    'order_created_owner' => [
        'pattern_id' => '233577',
        'title' => 'درخواست رزرو جدید — میزبان',
        'recipient' => 'میزبان',
        'trigger' => 'ایجاد سفارش (رزرو)',
        'source' => 'OrderObserver::created',
        'category' => 'orders',
        'parameters' => ['COUNT', 'START-DATE', 'END-DATE', 'AMOUNT'],
    ],
    'order_created_admin' => [
        'pattern_id' => config('sms.patterns.order_created_admin'),
        'title' => 'درخواست رزرو جدید — ادمین',
        'recipient' => 'ادمین (دریافت پیامک همیشگی و نوبتی)',
        'trigger' => 'ایجاد سفارش (رزرو)',
        'source' => 'OrderObserver::created',
        'category' => 'orders',
        'parameters' => ['ID', 'COUNT', 'START_DATE', 'END_DATE', 'AMOUNT', 'GUEST_NAME', 'GUEST_MOBILE', 'OWNER_NAME', 'OWNER_MOBILE', 'CALENDAR_LINK'],
    ],
    'order_awaiting_payment' => [
        'pattern_id' => '328688',
        'title' => 'در انتظار پرداخت',
        'recipient' => 'مهمان',
        'trigger' => 'تغییر وضعیت به «در انتظار پرداخت»',
        'source' => 'OrderObserver::updated',
        'category' => 'orders',
        'parameters' => ['ID'],
    ],
    'order_canceled' => [
        'pattern_id' => '356697',
        'title' => 'لغو رزرو',
        'recipient' => 'مهمان و میزبان',
        'trigger' => 'تغییر وضعیت به «لغو شده»',
        'source' => 'OrderObserver::updated',
        'category' => 'orders',
        'parameters' => ['ID'],
    ],
    'order_rejected' => [
        'pattern_id' => '277906',
        'title' => 'رد درخواست رزرو',
        'recipient' => 'مهمان',
        'trigger' => 'تغییر وضعیت به «رد شده»',
        'source' => 'OrderObserver::updated',
        'category' => 'orders',
        'parameters' => ['HOME-NAME'],
    ],
    'order_waiting_for_renter' => [
        'pattern_id' => '588298',
        'title' => 'تأیید رزرو — اطلاع به میزبان',
        'recipient' => 'میزبان',
        'trigger' => 'تغییر وضعیت به «در انتظار مهمان»',
        'source' => 'OrderObserver::updated',
        'category' => 'orders',
        'parameters' => ['ID', 'START-DATE', 'END-DATE', 'AMOUNT', 'USERNAME', 'MOBILE'],
    ],
    'before_residence' => [
        'pattern_id' => '810272',
        'title' => 'یادآوری قبل از اقامت',
        'recipient' => 'مهمان',
        'trigger' => 'زمان‌بندی روزانه (۲ روز قبل از شروع)',
        'source' => 'SendBeforResidenceSMS',
        'category' => 'scheduled',
        'parameters' => ['ID'],
    ],
    'after_residence' => [
        'pattern_id' => '928220',
        'title' => 'پس از پایان اقامت',
        'recipient' => 'مهمان',
        'trigger' => 'زمان‌بندی روزانه (روز پایان اقامت)',
        'source' => 'SendAfterResidenceSMS',
        'category' => 'scheduled',
        'parameters' => ['ID'],
    ],
    'login_otp' => [
        'pattern_id' => '120268',
        'title' => 'کد ورود یکبارمصرف',
        'recipient' => 'کاربر',
        'trigger' => 'درخواست ورود با موبایل',
        'source' => 'LoginTempController::send',
        'category' => 'auth',
        'parameters' => ['CODE'],
    ],
];
