<?php

return [
    'order_created_renter' => [
        'pattern_id' => config('sms.patterns.order_created_renter'),
        'title' => 'ثبت درخواست رزرو — مهمان',
        'recipient' => 'مهمان',
        'trigger' => 'ایجاد سفارش (رزرو)',
        'source' => 'OrderObserver::created',
        'category' => 'orders',
        'parameters' => ['HOME_NAME', 'CONSULTANT_NAME', 'CONSULTANT_MOBILE'],
        'description' => 'مشاور شما (%CONSULTANT_NAME%) — برای سوالات بیشتر با مشاور خود تماس بگیرید: %CONSULTANT_MOBILE%',
        'inbox_body' => "درخواست رزرو شما برای اقامتگاه «%HOME_NAME%» ثبت شد.\nمشاور شما %CONSULTANT_NAME% است. برای سؤال یا هماهنگی با این شماره تماس بگیرید: %CONSULTANT_MOBILE%\nمنتظر تأیید میزبان بمانید. نتیجه را همین‌جا و با پیامک به شما خبر می‌دهیم.%RENT_LINK_LINE%",
    ],
    'order_created_owner' => [
        'pattern_id' => config('sms.patterns.order_created_owner'),
        'title' => 'درخواست رزرو جدید — میزبان',
        'recipient' => 'میزبان',
        'trigger' => 'ایجاد سفارش (رزرو)',
        'source' => 'OrderObserver::created',
        'category' => 'orders',
        'parameters' => ['COUNT', 'START-DATE', 'END-DATE', 'AMOUNT'],
        'inbox_body' => "یک درخواست رزرو جدید برای اقامتگاه شما آمده است.\nتعداد مهمان: %COUNT%\nورود: %START-DATE%\nخروج: %END-DATE%\nمبلغ تسویه شما: %AMOUNT% تومان\nلطفاً هرچه زودتر درخواست را تأیید یا رد کنید. اگر تا ۳۰ دقیقه پاسخ ندهید، درخواست لغو می‌شود.%ORDER_LINK_LINE%",
    ],
    'order_created_admin' => [
        'pattern_id' => config('sms.patterns.order_created_admin'),
        'title' => 'درخواست رزرو جدید — ادمین',
        'recipient' => 'ادمین (دریافت پیامک همیشگی و نوبتی)',
        'trigger' => 'ایجاد سفارش (رزرو)',
        'source' => 'OrderObserver::created',
        'category' => 'orders',
        'parameters' => ['ID', 'COUNT', 'START_DATE', 'END_DATE', 'AMOUNT', 'GUEST_NAME', 'GUEST_MOBILE', 'OWNER_NAME', 'OWNER_MOBILE', 'CALENDAR_LINK'],
        'description' => 'لینک تقویم در قالب: https://vilafarda.ir/#CALENDAR_LINK# (بدون اسلش بین ir و #). مقدار ارسالی: admin/homes/117/date',
    ],
    'order_awaiting_payment' => [
        'pattern_id' => config('sms.patterns.order_awaiting_payment'),
        'title' => 'در انتظار پرداخت',
        'recipient' => 'مهمان',
        'trigger' => 'تغییر وضعیت به «در انتظار پرداخت»',
        'source' => 'OrderObserver::updated',
        'category' => 'orders',
        'parameters' => ['ID'],
        'inbox_body' => "میزبان درخواست رزرو شما را تأیید کرد.\nکد اقامتگاه: %ID%\nالان باید هزینه رزرو را پرداخت کنید تا رزرو قطعی شود. اگر پرداخت را به تأخیر بیندازید، ممکن است رزرو لغو شود.%PAY_LINK_LINE%",
    ],
    'order_canceled' => [
        'pattern_id' => config('sms.patterns.order_canceled'),
        'title' => 'لغو رزرو',
        'recipient' => 'مهمان و میزبان',
        'trigger' => 'تغییر وضعیت به «لغو شده»',
        'source' => 'OrderObserver::updated',
        'category' => 'orders',
        'parameters' => ['ID'],
        'inbox_body' => "رزرو مربوط به اقامتگاه با کد %ID% لغو شد.\nاین رزرو دیگر فعال نیست. اگر مبلغی پرداخت کرده‌اید، وضعیت بازگشت وجه را از جزئیات همین رزرو یا با پشتیبانی پیگیری کنید.%ACTION_LINK_LINE%%SEARCH_LINK_LINE%",
    ],
    'order_rejected' => [
        'pattern_id' => config('sms.patterns.order_rejected'),
        'title' => 'رد درخواست رزرو',
        'recipient' => 'مهمان',
        'trigger' => 'تغییر وضعیت به «رد شده»',
        'source' => 'OrderObserver::updated',
        'category' => 'orders',
        'parameters' => ['HOME-NAME', 'REASON'],
        'description' => 'متغیر REASON علت رد درخواست است (اقامتگاه رزرو است / قیمت درست نیست / تعمیرات دارم).',
        'inbox_body' => "متأسفانه میزبان درخواست رزرو اقامتگاه «%HOME-NAME%» را رد کرد.\nعلت اعلام‌شده: %REASON%\nاین درخواست دیگر قابل پرداخت نیست. می‌توانید اقامتگاه دیگری انتخاب کنید یا برای همان مقصد تاریخ دیگری رزرو کنید.%SEARCH_LINK_LINE%",
    ],
    'order_pending_timeout_owner' => [
        'pattern_id' => config('sms.patterns.order_pending_timeout_owner'),
        'title' => 'عدم پاسخ به درخواست — بسته‌شدن تقویم (میزبان)',
        'recipient' => 'میزبان',
        'trigger' => 'اتمام مهلت پاسخ میزبان (۳۰ دقیقه) و لغو خودکار درخواست',
        'source' => 'OrderObserver::updated',
        'category' => 'orders',
        'parameters' => ['HOST-NAME', 'HOME-NAME', 'CALENDAR-LINK'],
        'description' => 'HOST-NAME نام و نام‌خانوادگی میزبان است. لینک تقویم در قالب: https://vilafarda.ir/#CALENDAR-LINK# (مقدار ارسالی مثل hc/117).',
        'inbox_body' => "میزبان گرامی %HOST-NAME%\nشما به درخواست رزرو اقامتگاه «%HOME-NAME%» تا ۳۰ دقیقه پاسخ ندادید؛ به همین دلیل درخواست لغو شد و آن تاریخ‌ها در تقویم بسته شدند تا دوباره رزرو روی‌هم نیفتد.\nلطفاً روزهای آزاد را دوباره باز کنید.%CALENDAR_LINK_LINE%",
    ],
    'order_waiting_for_renter' => [
        'pattern_id' => config('sms.patterns.order_waiting_for_renter'),
        'title' => 'تأیید رزرو — اطلاع به میزبان',
        'recipient' => 'میزبان',
        'trigger' => 'تغییر وضعیت به «در انتظار مهمان»',
        'source' => 'OrderObserver::updated',
        'category' => 'orders',
        'parameters' => ['ID', 'START-DATE', 'END-DATE', 'AMOUNT', 'USERNAME', 'MOBILE'],
        'inbox_body' => "شما درخواست رزرو را تأیید کردید و الان منتظر پرداخت مهمان هستید.\nکد اقامتگاه: %ID%\nورود: %START-DATE%\nخروج: %END-DATE%\nمبلغ تسویه شما: %AMOUNT% تومان\nمهمان: %USERNAME%\nموبایل مهمان: %MOBILE%\nبعد از پرداخت مهمان، رزرو قطعی می‌شود.%ORDER_LINK_LINE%",
    ],
    'before_residence' => [
        'pattern_id' => config('sms.patterns.before_residence'),
        'title' => 'یادآوری قبل از اقامت',
        'recipient' => 'مهمان',
        'trigger' => 'زمان‌بندی روزانه (۲ روز قبل از شروع)',
        'source' => 'SendBeforResidenceSMS',
        'category' => 'scheduled',
        'parameters' => ['ID'],
        'inbox_body' => "یادآوری سفر: کمتر از ۴۸ ساعت تا ورود شما به اقامتگاه با کد %ID% مانده است.\nلطفاً ساعت ورود، وسایل لازم و هماهنگی با میزبان را دوباره بررسی کنید تا روز ورود مشکلی پیش نیاید.%RENT_LINK_LINE%",
    ],
    'after_residence' => [
        'pattern_id' => config('sms.patterns.after_residence'),
        'title' => 'پس از پایان اقامت',
        'recipient' => 'مهمان',
        'trigger' => 'زمان‌بندی روزانه (روز پایان اقامت)',
        'source' => 'SendAfterResidenceSMS',
        'category' => 'scheduled',
        'parameters' => ['ID'],
        'inbox_body' => "سفر شما به پایان رسیده است.\nاگر از اقامتگاه راضی بودید یا نکته‌ای داشتید، امتیاز و نظر بگذارید. نظر شما به میزبان و مهمان‌های بعدی کمک می‌کند.%REVIEW_LINK_LINE%",
    ],
    'login_otp' => [
        'pattern_id' => config('sms.patterns.login_otp'),
        'title' => 'کد ورود یکبارمصرف',
        'recipient' => 'کاربر',
        'trigger' => 'درخواست ورود با موبایل',
        'source' => 'LoginTempController::send',
        'category' => 'auth',
        'parameters' => ['CODE'],
        'description' => 'برای autofill خودکار در اندروید، انتهای متن پیامک باید شامل @vilafarda.ir #CODE باشد (مثال: کد ورود شما 12345 @vilafarda.ir #12345)',
    ],
    'home_submitted_host' => [
        'pattern_id' => config('sms.patterns.home_submitted_host'),
        'title' => 'ثبت اقامتگاه — میزبان',
        'recipient' => 'میزبان',
        'trigger' => 'ارسال اقامتگاه برای بررسی (خروج از پیش‌نویس، وضعیت در حال بررسی)',
        'source' => 'HomeObserver::updated',
        'category' => 'homes',
        'parameters' => ['HOST-NAME'],
        'description' => 'میزبان گرامی %HOST-NAME% اقامتگاه شما ثبت شد و پس از تایید در صفحه ما نمایش داده می‌شود. امیدواریم همکاری خوبی با هم داشته باشیم. در صورت طولانی شدن این روند با پشتیبانی در تماس باشید.',
        'inbox_body' => "میزبان گرامی %HOST-NAME%\nاقامتگاه شما برای بررسی ارسال شد. تا وقتی تیم ویلا فردا آن را تأیید کند، در سایت نمایش داده نمی‌شود.\nنتیجه بازبینی را همین‌جا به شما خبر می‌دهیم. اگر این مرحله طول کشید، با پشتیبانی تماس بگیرید.%HOME_LINK_LINE%",
    ],
    'home_submitted_admin' => [
        'pattern_id' => config('sms.patterns.home_submitted_admin'),
        'title' => 'ثبت اقامتگاه — ادمین',
        'recipient' => 'ادمین (دریافت پیامک همیشگی و نوبتی)',
        'trigger' => 'ارسال اقامتگاه برای بررسی (خروج از پیش‌نویس، وضعیت در حال بررسی)',
        'source' => 'HomeObserver::updated',
        'category' => 'homes',
        'parameters' => ['ADMIN-NAME'],
        'description' => 'ادمین گرامی %ADMIN-NAME% اقامتگاه جدیدی ثبت شده است. لطفاً آن را بررسی و تایید یا رد کنید.',
    ],
    'home_reviewed_host' => [
        'pattern_id' => config('sms.patterns.home_reviewed_host'),
        'title' => 'نتیجه بازبینی اقامتگاه — میزبان',
        'recipient' => 'میزبان',
        'trigger' => 'تغییر وضعیت از «در حال بررسی» به «تایید شده» یا «رد شده»',
        'source' => 'HomeObserver::updated',
        'category' => 'homes',
        'parameters' => ['HOST-NAME', 'REVIEW-RESULT'],
        'description' => 'میزبان گرامی %HOST-NAME% اقامتگاه شما توسط تیم ما بازبینی شده و %REVIEW-RESULT%. اگر سوالی دارید با شماره‌های پشتیبانی در تماس باشید. مقدار REVIEW-RESULT: تایید شد / رد شد.',
        'inbox_body' => "میزبان گرامی %HOST-NAME%\nاقامتگاه شما بازبینی شد و نتیجه آن «%REVIEW-RESULT%» است.\nاگر تأیید شده، اقامتگاه در سایت نمایش داده می‌شود و می‌توانید تقویم و قیمت را مدیریت کنید. اگر رد شده، جزئیات را ببینید و در صورت نیاز با پشتیبانی تماس بگیرید.%HOME_LINK_LINE%",
    ],
];
