<?php

return [
    'order_created_renter' => [
        'pattern_id' => config('sms.patterns.order_created_renter'),
        'title' => 'ثبت درخواست رزرو — مهمان',
        'recipient' => 'مهمان',
        'trigger' => 'ایجاد سفارش (رزرو)',
        'source' => 'OrderObserver::created',
        'category' => 'orders',
        'parameters' => ['HOME_NAME', 'CONSULTANT_NAME', 'CONSULTANT_MOBILE'],
        'description' => 'مشاور شما (%CONSULTANT_NAME%) — برای سوالات بیشتر با مشاور خود تماس بگیرید: %CONSULTANT_MOBILE%',
    ],
    'order_created_owner' => [
        'pattern_id' => config('sms.patterns.order_created_owner'),
        'title' => 'درخواست رزرو جدید — میزبان',
        'recipient' => 'میزبان',
        'trigger' => 'ایجاد سفارش (رزرو)',
        'source' => 'OrderObserver::created',
        'category' => 'orders',
        'parameters' => ['COUNT', 'START-DATE', 'END-DATE', 'AMOUNT'],
    ],
    'order_created_admin' => [
        'pattern_id' => config('sms.patterns.order_created_admin'),
        'title' => 'درخواست رزرو جدید — ادمین',
        'recipient' => 'ادمین (دریافت پیامک همیشگی و نوبتی)',
        'trigger' => 'ایجاد سفارش (رزرو)',
        'source' => 'OrderObserver::created',
        'category' => 'orders',
        'parameters' => ['ID', 'COUNT', 'START_DATE', 'END_DATE', 'AMOUNT', 'GUEST_NAME', 'GUEST_MOBILE', 'OWNER_NAME', 'OWNER_MOBILE', 'CALENDAR_LINK'],
        'description' => 'لینک تقویم در قالب: https://vilafarda.ir/#CALENDAR_LINK# (بدون اسلش بین ir و #). مقدار ارسالی: admin/homes/117/date',
    ],
    'order_awaiting_payment' => [
        'pattern_id' => config('sms.patterns.order_awaiting_payment'),
        'title' => 'در انتظار پرداخت',
        'recipient' => 'مهمان',
        'trigger' => 'تغییر وضعیت به «در انتظار پرداخت»',
        'source' => 'OrderObserver::updated',
        'category' => 'orders',
        'parameters' => ['ID'],
    ],
    'order_canceled' => [
        'pattern_id' => config('sms.patterns.order_canceled'),
        'title' => 'لغو رزرو',
        'recipient' => 'مهمان و میزبان',
        'trigger' => 'تغییر وضعیت به «لغو شده»',
        'source' => 'OrderObserver::updated',
        'category' => 'orders',
        'parameters' => ['ID'],
    ],
    'order_rejected' => [
        'pattern_id' => config('sms.patterns.order_rejected'),
        'title' => 'رد درخواست رزرو',
        'recipient' => 'مهمان',
        'trigger' => 'تغییر وضعیت به «رد شده»',
        'source' => 'OrderObserver::updated',
        'category' => 'orders',
        'parameters' => ['HOME-NAME', 'REASON'],
        'description' => 'متغیر REASON علت رد درخواست است (اقامتگاه رزرو است / قیمت درست نیست / تعمیرات دارم).',
    ],
    'order_pending_timeout_owner' => [
        'pattern_id' => config('sms.patterns.order_pending_timeout_owner'),
        'title' => 'عدم پاسخ به درخواست — بسته‌شدن تقویم (میزبان)',
        'recipient' => 'میزبان',
        'trigger' => 'اتمام مهلت پاسخ میزبان (۳۰ دقیقه) و لغو خودکار درخواست',
        'source' => 'OrderObserver::updated',
        'category' => 'orders',
        'parameters' => ['HOST-NAME', 'HOME-NAME', 'CALENDAR-LINK'],
        'description' => 'HOST-NAME نام و نام‌خانوادگی میزبان است. لینک تقویم در قالب: https://vilafarda.ir/#CALENDAR-LINK# (مقدار ارسالی مثل hc/117).',
    ],
    'order_waiting_for_renter' => [
        'pattern_id' => config('sms.patterns.order_waiting_for_renter'),
        'title' => 'تأیید رزرو — اطلاع به میزبان',
        'recipient' => 'میزبان',
        'trigger' => 'تغییر وضعیت به «در انتظار مهمان»',
        'source' => 'OrderObserver::updated',
        'category' => 'orders',
        'parameters' => ['ID', 'START-DATE', 'END-DATE', 'AMOUNT', 'USERNAME', 'MOBILE'],
    ],
    'before_residence' => [
        'pattern_id' => config('sms.patterns.before_residence'),
        'title' => 'یادآوری قبل از اقامت',
        'recipient' => 'مهمان',
        'trigger' => 'زمان‌بندی روزانه (۲ روز قبل از شروع)',
        'source' => 'SendBeforResidenceSMS',
        'category' => 'scheduled',
        'parameters' => ['ID'],
    ],
    'after_residence' => [
        'pattern_id' => config('sms.patterns.after_residence'),
        'title' => 'پس از پایان اقامت',
        'recipient' => 'مهمان',
        'trigger' => 'زمان‌بندی روزانه (روز پایان اقامت)',
        'source' => 'SendAfterResidenceSMS',
        'category' => 'scheduled',
        'parameters' => ['ID'],
    ],
    'login_otp' => [
        'pattern_id' => config('sms.patterns.login_otp'),
        'title' => 'کد ورود یکبارمصرف',
        'recipient' => 'کاربر',
        'trigger' => 'درخواست ورود با موبایل',
        'source' => 'LoginTempController::send',
        'category' => 'auth',
        'parameters' => ['CODE'],
        'description' => 'برای autofill خودکار در اندروید، انتهای متن پیامک باید شامل @vilafarda.ir #CODE باشد (مثال: کد ورود شما 12345 @vilafarda.ir #12345)',
    ],
];
